// <auto-generated />
using Devs2Blu.APIFilmes.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Devs2Blu.APIFilmes.Infra.Data.Migrations
{
    [DbContext(typeof(SQLServerContext))]
    partial class SQLServerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Devs2Blu.APIFilmes.Domain.Entities.Movies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Pikachu vira um detetive nessa empolgante aventura Pokemon",
                            Rating = 12,
                            Title = "Pokemon: Detetive Pikachu"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Acompanhe Miles Morales no multiverso com varios Spider-Mans",
                            Rating = 12,
                            Title = "Spider-Man: Into The SpiderVerse"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Acompanhe os Avengers nessa emboscada contra Thanos, que esta na busca das joias do infinito",
                            Rating = 14,
                            Title = "Avengers: Infinity War"
                        },
                        new
                        {
                            Id = 4,
                            Description = "O que os animais de estimação fazem quando não estamos presentes? Descubra em PETS",
                            Rating = 0,
                            Title = "Pets"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Acompanhe carros em alta velocidade e manobras nesta obra baseada no videogame",
                            Rating = 14,
                            Title = "Need For Speed"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Corridas com drift te esperam na iluminada Tokyo",
                            Rating = 16,
                            Title = "Fast and Furious: Tokyo Drift"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Embarque na nave Milano e acompanhe um comico grupo de herois",
                            Rating = 10,
                            Title = "Guardians Of The Galaxy"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Veja o antiheroi Deadpool em uma comédia triste e cheia de ação",
                            Rating = 18,
                            Title = "Deadpool 2"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Um grupo de vilões condenados luta para salvar o mundo",
                            Rating = 16,
                            Title = "Suicide Squad"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Veja a triste origem do Coringa, famoso vilão da DC Comics",
                            Rating = 18,
                            Title = "Joker"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
