// <auto-generated />
using Devs2Blu.ProjetosAula.Atividade4MVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Devs2Blu.ProjetosAula.Atividade4MVC.Migrations
{
    [DbContext(typeof(ContextoDatabase))]
    [Migration("20221216002527_Inicial-Tabelas")]
    partial class InicialTabelas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Devs2Blu.ProjetosAula.Atividade4MVC.Models.Entities.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("generos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Ação/Aventura"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Corrida"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Esporte"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "FPS"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "RPG"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Plataforma"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Terror"
                        });
                });

            modelBuilder.Entity("Devs2Blu.ProjetosAula.Atividade4MVC.Models.Entities.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GeneroId")
                        .HasColumnType("int")
                        .HasColumnName("GeneroId");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome");

                    b.Property<double>("Nota")
                        .HasColumnType("float")
                        .HasColumnName("nota");

                    b.Property<string>("Personagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("personagem");

                    b.Property<string>("Rewiew")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("review");

                    b.HasKey("Id");

                    b.HasIndex("GeneroId");

                    b.ToTable("jogos");
                });

            modelBuilder.Entity("Devs2Blu.ProjetosAula.Atividade4MVC.Models.Entities.Jogo", b =>
                {
                    b.HasOne("Devs2Blu.ProjetosAula.Atividade4MVC.Models.Entities.Genero", "Genero")
                        .WithMany("Jogo")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("Devs2Blu.ProjetosAula.Atividade4MVC.Models.Entities.Genero", b =>
                {
                    b.Navigation("Jogo");
                });
#pragma warning restore 612, 618
        }
    }
}
