// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoContatos.API.Context;

#nullable disable

namespace ProjetoContatos.API.Migrations
{
    [DbContext(typeof(SQLServerContext))]
    partial class SQLServerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetoContatos.API.Entities.Contato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contatos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bairro = "Vila Itoupava",
                            Cidade = "Blumenau",
                            Estado = "SC",
                            Nome = "Tuca",
                            Telefone = "(47) 99457-8964"
                        },
                        new
                        {
                            Id = 2,
                            Bairro = "Vila Itoupava",
                            Cidade = "Blumenau",
                            Estado = "SC",
                            Nome = "Mel",
                            Telefone = "(47) 99657-8212"
                        },
                        new
                        {
                            Id = 3,
                            Bairro = "Vila Itoupava",
                            Cidade = "Blumenau",
                            Estado = "SC",
                            Nome = "Zuky",
                            Telefone = "(47) 99123-8785"
                        },
                        new
                        {
                            Id = 4,
                            Bairro = "Vila Itoupava",
                            Cidade = "Blumenau",
                            Estado = "SC",
                            Nome = "Bidu",
                            Telefone = "(47) 99932-7452"
                        },
                        new
                        {
                            Id = 5,
                            Bairro = "Vila Itoupava",
                            Cidade = "Blumenau",
                            Estado = "SC",
                            Nome = "Lilica",
                            Telefone = "(47) 99445-6787"
                        },
                        new
                        {
                            Id = 6,
                            Bairro = "Vila Itoupava",
                            Cidade = "Blumenau",
                            Estado = "SC",
                            Nome = "Nickolas",
                            Telefone = "(47) 99985-8554"
                        },
                        new
                        {
                            Id = 7,
                            Bairro = "Vila Itoupava",
                            Cidade = "Blumenau",
                            Estado = "SC",
                            Nome = "Nanica",
                            Telefone = "(47) 99457-8545"
                        },
                        new
                        {
                            Id = 8,
                            Bairro = "Vila Itoupava",
                            Cidade = "Blumenau",
                            Estado = "SC",
                            Nome = "Peta",
                            Telefone = "(47) 99145-1225"
                        },
                        new
                        {
                            Id = 9,
                            Bairro = "Vila Itoupava",
                            Cidade = "Blumenau",
                            Estado = "SC",
                            Nome = "Mingui",
                            Telefone = "(47) 99487-5412"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
